// Generates src/brand.generated.ts from the brand's tokens (company decision 0018): the landing and
// docs pages read the brand's semantic roles (var(--volter-*)), never literal colours. tokens.css and
// its faces are fetched here, at build time, and bundled into the Worker, which serves the faces at
// /fonts/<file>; the pages never depend on brand.volter.ai at runtime. A failed fetch fails the build.
import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BRAND = 'https://brand.volter.ai';
const out = resolve(dirname(fileURLToPath(import.meta.url)), '../src/brand.generated.ts');

const fetched = async (path) => {
  const response = await fetch(`${BRAND}${path}`);
  if (!response.ok) throw new Error(`brand ${path}: HTTP ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
};

const tokens = (await fetched('/tokens.css')).toString('utf8').replaceAll(`${BRAND}/fonts/`, '/fonts/');
const faces = [...tokens.matchAll(/url\("\/fonts\/([^"]+)"\)/g)].map((m) => m[1]);
if (faces.length === 0) throw new Error('brand tokens.css names no faces');
const fonts = {};
for (const face of faces) fonts[face] = (await fetched(`/fonts/${face}`)).toString('base64');

await writeFile(
  out,
  `// Generated by scripts/brand-tokens.mjs from ${BRAND}/tokens.css; do not edit, not committed.\n` +
    `export const BRAND_TOKENS_CSS = ${JSON.stringify(tokens)};\n` +
    `export const BRAND_FONTS: Record<string, string> = ${JSON.stringify(fonts)};\n`,
);
console.log(`brand tokens: src/brand.generated.ts with tokens.css and ${faces.length} faces`);
